# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/taller_nbdev_simple',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/taller_nbdev_simple',
                'lib_path': 'taller_nbdev_simple'},
  'syms': {'taller_nbdev_simple.core': {'taller_nbdev_simple.core.foo': ('core.html#foo', 'taller_nbdev_simple/core.py')}}}
