# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'saludo', 'saludo_a', 'concatena_saludos']

# %% ../nbs/00_core.ipynb 3
def foo(var_boo):
    """
    Esta funcion muestra si la variable es verdadera o falsa
    """
    if var_boo:
        print("Es verdadera")
    else:
        print("Es falsa")
    return 

# %% ../nbs/00_core.ipynb 7
def saludo():
    """Imprime Hola"""
    print('Hola!')
    return

# %% ../nbs/00_core.ipynb 9
def saludo_a(to):
    """Imprime hola a un nombre"""
    print('Hola!', to)
    
    print('Espero que te encuentres bien')
    return

# %% ../nbs/00_core.ipynb 13
def concatena_saludos(nombre = None):
    """Es una función que concatena las dos funciones"""
    saludo()
    saludo_a(nombre)
    
