# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb 3
def foo(var_boo):
    """
    Esta funcion muestra ssi la variable es verdadera o falsa
    """
    if var_boo:
        print("Es verdadera")
    else:
        print("Es falsa")
    return 
